export const costDimensions = [
  { value: 'date', key: 'dimension', label: 'Date', clearableValue: false },
  { value: 'day', key: 'dimension', label: 'Day', clearableValue: false },
  { value: 'day_of_week', key: 'dimension', label: 'Day of Week', clearableValue: false },
  { value: 'year', key: 'dimension', label: 'Year', clearableValue: false },
  { value: 'month', key: 'dimension', label: 'Month (Category)', clearableValue: false },
  { value: 'year_month', key: 'dimension', label: 'Month (Year)', clearableValue: false },
  { value: 'week', key: 'dimension', label: 'Week (Category)', clearableValue: false },
  { value: 'year_week', key: 'dimension', label: 'Week (Year)', clearableValue: false },
  { value: 'compute_usage_type', key: 'dimension', label: 'Compute Usage Type', clearableValue: false },
  { value: 'engine', key: 'dimension', label: 'Engine', clearableValue: false },
  { value: 'instance_category', key: 'dimension', label: 'Instance Category', clearableValue: false },
  { value: 'instance_family', key: 'dimension', label: 'Instance Family', clearableValue: false },
  { value: 'instance_size', key: 'dimension', label: 'Instance Size', clearableValue: false },
  { value: 'instance_type', key: 'dimension', label: 'Instance Type', clearableValue: false },
  { value: 'lease_type', key: 'dimension', label: 'Lease Type', clearableValue: false },
  { value: 'operating_system', key: 'dimension', label: 'Operating System', clearableValue: false },
  { value: 'operation', key: 'dimension', label: 'Operation', clearableValue: false },
  { value: 'reservation_identifier', key: 'dimension', label: 'Reservation ID', clearableValue: false },
  { value: 'resource_identifier', key: 'dimension', label: 'Resource ID', clearableValue: false },
  { value: 'transaction_type', key: 'dimension', label: 'Transaction Type', clearableValue: false },
  { value: 'usage_family', key: 'dimension', label: 'Usage Family', clearableValue: false },
  { value: 'usage_type', key: 'dimension', label: 'Usage Type', clearableValue: false },
  { value: 'vendor_account_identifier', key: 'dimension', label: 'Account ID', clearableValue: false },
  { value: 'vendor_account_name', key: 'dimension', label: 'Account Name', clearableValue: false },
  { value: 'region_zone', key: 'dimension', label: 'Availability Zone', clearableValue: false },
  { value: 'item_description', key: 'dimension', label: 'Item Description', clearableValue: false },
  { value: 'account_identifier', key: 'dimension', label: 'Payer Account ID', clearableValue: false },
  { value: 'account_name', key: 'dimension', label: 'Payer Account Name', clearableValue: false },
  { value: 'service_name', key: 'dimension', label: 'Product Name', clearableValue: false },
  { value: 'region', key: 'dimension', label: 'Region', clearableValue: false },
  { value: 'seller', key: 'dimension', label: 'Seller', clearableValue: false },
  { value: 'enhanced_service_name', key: 'dimension', label: 'Service Name', clearableValue: false },
  { value: 'vendor', key: 'dimension', label: 'Vendor', clearableValue: false },
  { value: 'zone', key: 'dimension', label: 'Zone', clearableValue: false },
]