export const costDimensions = [
  { value: 'date', key: 'dimension', label: 'Date', clearableValue: false },
  { value: 'day', key: 'dimension', label: 'Day', clearableValue: false },
  { value: 'day_of_week', key: 'dimension', label: 'Day of Week', clearableValue: false },
  { value: 'year', key: 'dimension', label: 'Year', clearableValue: false },
  { value: 'month', key: 'dimension', label: 'Month (Category)', clearableValue: false },
  { value: 'year_month', key: 'dimension', label: 'Month (Year)', clearableValue: false },
  { value: 'week', key: 'dimension', label: 'Week (Category)', clearableValue: false },
  { value: 'year_week', key: 'dimension', label: 'Week (Year)', clearableValue: false },
  { value: 'compute_usage_type', key: 'dimension', label: 'Compute Usage Type', clearableValue: false },
  { value: 'engine', key: 'dimension', label: 'Engine', clearableValue: false },
  { value: 'instance_category', key: 'dimension', label: 'Instance Category', clearableValue: false },
  { value: 'instance_family', key: 'dimension', label: 'Instance Family', clearableValue: false },
  { value: 'instance_size', key: 'dimension', label: 'Instance Size', clearableValue: false },
  { value: 'instance_type', key: 'dimension', label: 'Instance Type', clearableValue: false },
  { value: 'lease_type', key: 'dimension', label: 'Lease Type', clearableValue: false },
  { value: 'operating_system', key: 'dimension', label: 'Operating System', clearableValue: false },
  { value: 'operation', key: 'dimension', label: 'Operation', clearableValue: false },
  { value: 'reservation_identifier', key: 'dimension', label: 'Reservation ID', clearableValue: false },
  { value: 'resource_identifier', key: 'dimension', label: 'Resource ID', clearableValue: false },
  { value: 'transaction_type', key: 'dimension', label: 'Transaction Type', clearableValue: false },
  { value: 'usage_family', key: 'dimension', label: 'Usage Family', clearableValue: false },
  { value: 'usage_type', key: 'dimension', label: 'Usage Type', clearableValue: false },
  { value: 'vendor_account_identifier', key: 'dimension', label: 'Account ID', clearableValue: false },
  { value: 'vendor_account_name', key: 'dimension', label: 'Account Name', clearableValue: false },
  { value: 'region_zone', key: 'dimension', label: 'Availability Zone', clearableValue: false },
  { value: 'item_description', key: 'dimension', label: 'Item Description', clearableValue: false },
  { value: 'account_identifier', key: 'dimension', label: 'Payer Account ID', clearableValue: false },
  { value: 'account_name', key: 'dimension', label: 'Payer Account Name', clearableValue: false },
  { value: 'service_name', key: 'dimension', label: 'Product Name', clearableValue: false },
  { value: 'region', key: 'dimension', label: 'Region', clearableValue: false },
  { value: 'seller', key: 'dimension', label: 'Seller', clearableValue: false },
  { value: 'enhanced_service_name', key: 'dimension', label: 'Service Name', clearableValue: false },
  { value: 'vendor', key: 'dimension', label: 'Vendor', clearableValue: false },
  { value: 'zone', key: 'dimension', label: 'Zone', clearableValue: false },
]

export const utilDimensions = [
  { value: 'date', key: 'dimension', label: 'Date', clearableValue: false },
  { value: 'day', key: 'dimension', label: 'Day', clearableValue: false },
  { value: 'day_of_week', key: 'dimension', label: 'Day of Week', clearableValue: false },
  { value: 'year', key: 'dimension', label: 'Year', clearableValue: false },
  { value: 'month', key: 'dimension', label: 'Month', clearableValue: false },
  { value: 'week', key: 'dimension', label: 'Week', clearableValue: false },
  { value: 'hour', key: 'dimension', label: 'Hour', clearableValue: false },
  { value: 'launch_date', key: 'dimension', label: 'Launch Date', clearableValue: false },
  { value: 'launch_day', key: 'dimension', label: 'Launch Day', clearableValue: false },
  { value: 'launch_day_of_week', key: 'dimension', label: 'Launch Day of Week', clearableValue: false },
  { value: 'launch_month', key: 'dimension', label: 'Launch Month', clearableValue: false },
  { value: 'launch_time', key: 'dimension', label: 'Launch Time', clearableValue: false },
  { value: 'launch_week', key: 'dimension', label: 'Launch Week', clearableValue: false },
  { value: 'launch_year', key: 'dimension', label: 'Launch Year', clearableValue: false },
  { value: 'zone', key: 'dimension', label: 'Zone', clearableValue: false },
  { value: 'attached_instance_id', key: 'dimension', label: 'Attached Instance Identifier', clearableValue: false },
  { value: 'region_zone', key: 'dimension', label: 'Availability Zone', clearableValue: false },
  { value: 'instance_category', key: 'dimension', label: 'Instance Category', clearableValue: false },
  { value: 'region', key: 'dimension', label: 'Region', clearableValue: false },
  { value: 'instance_identifier', key: 'dimension', label: 'Instance ID', clearableValue: false },
  { value: 'instance_name', key: 'dimension', label: 'Instance Name', clearableValue: false },
  { value: 'instance_size', key: 'dimension', label: 'Instance Type', clearableValue: false },
  { value: 'table_name', key: 'dimension', label: 'Table Name', clearableValue: false },
  { value: 'tenancy', key: 'dimension', label: 'Tenancy', clearableValue: false },
  { value: 'volume_identifier', key: 'dimension', label: 'Volume Identifier', clearableValue: false },
  { value: 'dns_name', key: 'dimension', label: 'DNS Name', clearableValue: false },
  { value: 'ip_address', key: 'dimension', label: 'IP Address', clearableValue: false },
  { value: 'private_dns_name', key: 'dimension', label: 'Private DNS Name', clearableValue: false },
  { value: 'private_ip_address', key: 'dimension', label: 'Private IP', clearableValue: false },
  { value: 'subnet', key: 'dimension', label: 'Subnet ID', clearableValue: false },
  { value: 'vpc_id', key: 'dimension', label: 'VPC Identifier', clearableValue: false },
  { value: 'architecture', key: 'dimension', label: 'Architecture', clearableValue: false },
  { value: 'operating_system', key: 'dimension', label: 'OS', clearableValue: false },
  { value: 'virtualization_type', key: 'dimension', label: 'Virtualization', clearableValue: false },
  { value: 'days_since_launch', key: 'dimension', label: 'Days Alive', clearableValue: false },
  { value: 'storage_type', key: 'dimension', label: 'Storage Type', clearableValue: false },
  { value: 'vendor_account_identifier', key: 'dimension', label: 'Account ID', clearableValue: false },
  { value: 'vendor_account_name', key: 'dimension', label: 'Account Name', clearableValue: false },
  { value: 'image', key: 'dimension', label: 'AMI', clearableValue: false },
  { value: 'product_name', key: 'dimension', label: 'Product Name', clearableValue: false },
  { value: 'security_group_id', key: 'dimension', label: 'Security Group ID', clearableValue: false },
  { value: 'security_group_name', key: 'dimension', label: 'Security Groups Names', clearableValue: false },
]